# Generated by Django 4.2.5 on 2023-10-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
