# Generated by Django 4.2.5 on 2023-10-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0003_booking_ticket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
