# Generated by Django 4.2.5 on 2023-10-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0004_alter_booking_seat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='seats_booked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
