# Generated by Django 4.2.5 on 2023-10-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0005_movie_seats_booked_movie_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_count',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
